package ui.views.main_window;

public class UserPreferences
{
    // CONVERTER
    public static final String CONVERTER_GOOGLE_LAST_OPEN_FOLDER_PATH = "CONVERTER_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String CONVERTER_INVOLVES_LAST_OPEN_FOLDER_PATH = "CONVERTER_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String CONVERTER_DYSRUP_LAST_OPEN_FOLDER_PATH = "CONVERTER_DYSRUP_LAST_OPEN_FOLDER_PATH";

    // PRODUCT UPDATE
    public static final String PRODUCTS_LAST_OPEN_FOLDER_PATH = "PRODUCTS_LAST_OPEN_FOLDER_PATH";
    public static final String ROUTES_LAST_OPEN_FOLDER_PATH = "ROUTES_LAST_OPEN_FOLDER_PATH";

    // SELMI
    public static final String SELMI_DYSRUP_LAST_OPEN_FOLDER_PATH = "SELMI_DYSRUP_LAST_OPEN_FOLDER_PATH";
    public static final String SELMI_GOOGLE_LAST_OPEN_FOLDER_PATH = "SELMI_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String SELMI_INVOLVES_LAST_OPEN_FOLDER_PATH = "SELMI_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String SELMI_REPORT_LAST_OPEN_FOLDER_PATH = "SELMI_REPORT_LAST_OPEN_FOLDER_PATH";

    // IGARAPE
    public static final String IGARAPE_DYSRUP_LAST_OPEN_FOLDER_PATH = "IGARAPE_DYSRUP_LAST_OPEN_FOLDER_PATH";
    public static final String IGARAPE_GOOGLE_LAST_OPEN_FOLDER_PATH = "IGARAPE_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String IGARAPE_INVOLVES_LAST_OPEN_FOLDER_PATH = "IGARAPE_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String IGARAPE_REPORT_USE_LAST_OPEN_FOLDER_PATH = "IGARAPE_REPORT_USE_LAST_OPEN_FOLDER_PATH";
    public static final String IGARAPE_REPORT_CLIENT_LAST_OPEN_FOLDER_PATH = "IGARAPE_REPORT_CLIENT_LAST_OPEN_FOLDER_PATH";

    // FROOTY
    public static final String FROOTY_DYSRUP_LAST_OPEN_FOLDER_PATH = "FROOTY_DYSRUP_LAST_OPEN_FOLDER_PATH";
    public static final String FROOTY_GOOGLE_LAST_OPEN_FOLDER_PATH = "FROOTY_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String FROOTY_INVOLVES_LAST_OPEN_FOLDER_PATH = "FROOTY_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String FROOTY_REPORT_LAST_OPEN_FOLDER_PATH = "FROOTY_REPORT_LAST_OPEN_FOLDER_PATH";

    // DE MARCHI
    public static final String DEMARCHI_DYSRUP_LAST_OPEN_FOLDER_PATH = "DEMARCHI_DYSRUP_LAST_OPEN_FOLDER_PATH";
    public static final String DEMARCHI_GOOGLE_LAST_OPEN_FOLDER_PATH = "DEMARCHI_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String DEMARCHI_GIV_LAST_OPEN_FOLDER_PATH = "DEMARCHI_GIV_LAST_OPEN_FOLDER_PATH";
    public static final String DEMARCHI_REPORT_LAST_OPEN_FOLDER_PATH = "DEMARCHI_REPORT_LAST_OPEN_FOLDER_PATH";

    // A LEITERIA
    public static final String ALEITERIA_GOOGLE_LAST_OPEN_FOLDER_PATH = "ALEITERIA_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String ALEITERIA_INVOLVES_LAST_OPEN_FOLDER_PATH = "ALEITERIA_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String ALEITERIA_REPORT_LAST_OPEN_FOLDER_PATH = "ALEITERIA_REPORT_LAST_OPEN_FOLDER_PATH";

    // CONGEBRAS
    public static final String CONGEBRAS_GOOGLE_LAST_OPEN_FOLDER_PATH = "CONGEBRAS_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String CONGEBRAS_INVOLVES_LAST_OPEN_FOLDER_PATH = "CONGEBRAS_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String CONGEBRAS_REPORT_LAST_OPEN_FOLDER_PATH = "CONGEBRAS_REPORT_LAST_OPEN_FOLDER_PATH";

    //MARIA ANGU
    public static final String MARIA_ANGU_GOOGLE_LAST_OPEN_FOLDER_PATH = "MARIA_ANGU_GOOGLE_LAST_OPEN_FOLDER_PATH";
    public static final String MARIA_ANGU_INVOLVES_LAST_OPEN_FOLDER_PATH = "MARIA_ANGU_INVOLVES_LAST_OPEN_FOLDER_PATH";
    public static final String MARIA_ANGU_REPORT_LAST_OPEN_FOLDER_PATH = "MARIA_ANGU_REPORT_LAST_OPEN_FOLDER_PATH";
}
